sudo: false

addons:
  apt:
    sources:
    - kalakris-cmake
    - kubuntu-backports
    - boost-latest
    packages:
    - cmake
    - libboost-dev

language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - BUILD_CONFIG=Release
  - BUILD_CONFIG=Debug

matrix:
  allow_failures:
    - compiler: clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then
    else
      sudo apt-cache search libboost;
      sudo locate libboost_system.so;
    fi

install:

before_script:
  - mkdir build.ci
  - cd build.ci
  - cmake .. -DBUILD_UT=ON -DCMAKE_BUILD_TYPE=$BUILD_CONFIG

script:
  - cmake --build .
  - ctest -VV

notifications:
  recipients:
  email:
    on_success: change
    on_failure: always
